version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: dev.to/mongodb
    volumes:
      - ./db_data/:/data/db/

#  worker:
#    container_name: worker
#    image: worker-image:latest
#    network_mode: host
#    stdin_open: true
#    tty: true
#  #    ports:
#  #      - 9080:9080

  model:
    container_name: model
    image: model-image:latest
    network_mode: host
    stdin_open: true
    tty: true
  #    ports:
  #      - 9082:9082

  persistence:
    container_name: persistence
    image: persistence-image:latest
    network_mode: host
    stdin_open: true
    tty: true
  #    ports:
  #      - 9083:9083

  controller:
    container_name: controller
    image: controller-image:latest
    network_mode: host
    stdin_open: true
    tty: true
  #    ports:
  #      - 9081:9081

  ui:
    container_name: ui
    image: ui-image:latest
    network_mode: host
    stdin_open: true
    tty: true
  #    ports:
  #      - 9088:9088
