services:

  model:
    container_name: model
    image: model-image:latest
    network_mode: host

  persistence:
    container_name: persistence
    image: persistence-image:latest
    network_mode: host

  controller:
    container_name: controller
    image: controller-image:latest
    network_mode: host

  ui:
    container_name: ui
    image: ui-image:latest
    network_mode: host

