
services:

  model:
    container_name: model
    build:
        context: ./
        dockerfile: model/Dockerfile
    image: model-assembly-image:latest
    network_mode: host
    stdin_open: true
    tty: true
  #    ports:
  #      - 9082:9082

  persistence:
    container_name: persistence
    build:
      context: ./
      dockerfile: persistence/Dockerfile
    image: persistence-assembly-image:latest
    network_mode: host
    stdin_open: true
    tty: true
  #    ports:
  #      - 9083:9083

  controller:
    container_name: controller
    build:
      context: ./
      dockerfile: controller/Dockerfile
    image: controller-assembly-image:latest
    network_mode: host
    stdin_open: true
    tty: true
  #    ports:
  #      - 9081:9081

  ui:
    container_name: ui
    build:
      context: ./
      dockerfile: ui/Dockerfile
    image: ui-assembly-image:latest
    network_mode: host
    stdin_open: true
    tty: true
    depends_on:
      - controller
      - persistence
      - model
  #    ports:
  #      - 9088:9088
