services:

  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tbl
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"

  model:
    container_name: model
    image: model-image:latest
    network_mode: host
    stdin_open: true
    tty: true
  #    ports:
  #      - 9082:9082

  persistence:
    container_name: persistence
    image: persistence-image:latest
    network_mode: host
    stdin_open: true
    tty: true
  #    ports:
  #      - 9083:9083

  controller:
    container_name: controller
    image: controller-image:latest
    network_mode: host
    stdin_open: true
    tty: true
  #    ports:
  #      - 9081:9081

  ui:
    container_name: ui
    image: ui-image:latest
    network_mode: host
    stdin_open: true
    tty: true
  #    ports:
  #      - 9088:9088
