name: Scala CI
on:
  push:
    branches:
      - SA_05_REST
  pull_request:
    branches:
      - SA_05_REST
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: compile
        run: sbt compile
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Project and export Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
         export CI_BRANCH="${GITHUB_REF#refs/heads/}"
         sbt jacocoAggregate
         sbt clean jacoco jacocoCoveralls
